# Generated by Django 5.1 on 2024-10-11 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('num_document', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('document_type', models.CharField(choices=[('AS', 'AS'), ('CC', 'CC'), ('CE', 'CE'), ('MS', 'MS'), ('NU', 'NU'), ('PA', 'PA'), ('PE', 'PE'), ('PT', 'PT'), ('RC', 'RC'), ('TI', 'TI')], default='CC', max_length=2)),
                ('role', models.CharField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('CAPACITACION', 'CAPACITACION'), ('INFORMES', 'INFORMES'), ('AUDITORIA', 'AUDITORIA'), ('CONTRATACION', 'CONTRATACION'), ('TESORERIA', 'TESORERIA'), ('GERENCIA', 'GERENCIA'), ('TI', 'TI')], default='ADMINISTRADOR', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ips', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('cod_ips', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubtypeRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subtype_request', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='typeRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typerequest', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_solicited', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('number', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('requirement', models.TextField(blank=True, default='', null=True, unique=True)),
                ('answer', models.TextField(blank=True, default='', null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_close', models.BooleanField(default=True)),
                ('how_it_conclude', models.TextField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('support_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('id_CustomerUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_CustomerUser', to='request.customeruser')),
                ('id_CustomerUser2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_CustomerUser2', to='request.customeruser')),
                ('id_ips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.ips')),
                ('subtype_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.subtyperequest')),
                ('typerequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.typerequest')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, default='', null=True, unique=True)),
                ('image', models.TextField(blank=True, default='', null=True, unique=True)),
                ('id_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.support')),
            ],
        ),
        migrations.AddField(
            model_name='subtyperequest',
            name='type_request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.typerequest'),
        ),
    ]
