# Generated by Django 5.1 on 2024-10-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_comments_id_alter_comments_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(blank=True, default='', null=True, unique=True),
        ),
    ]
