# Generated by Django 5.1 on 2024-10-31 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_comments_text'),
        ('request', '0004_ips_is_active_alter_comments_text'),
    ]

    operations = [
    ]
