# Generated by Django 5.1 on 2024-11-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_merge_20241031_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('CAPACITACION', 'CAPACITACION'), ('INFORMES', 'INFORMES'), ('AUDITORIA', 'AUDITORIA'), ('CONTRATACION', 'CONTRATACION'), ('TESORERIA', 'TESORERIA'), ('GERENCIA', 'GERENCIA'), ('TI', 'TI')], default='GERENCIA', max_length=15),
        ),
        migrations.AlterField(
            model_name='ips',
            name='cod_ips',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
