# Generated by Django 5.1 on 2024-11-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_support_role_alter_ips_cod_ips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='role',
            new_name='role2',
        ),
    ]
