# Generated by Django 5.1 on 2024-11-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_support_medio_alter_support_role2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='how_it_conclude',
            field=models.CharField(choices=[('EXISTOSO', 'EXISTOSO'), ('NO_EXISTOSO', 'NO_EXISTOSO'), ('EN_PROGRESO', 'EN_PROGRESO'), ('PENDIENTE', 'PENDIENTE')], default='EXISTOSO', max_length=30),
        ),
    ]
