# Generated by Django 5.1 on 2024-11-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_alter_support_how_it_conclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='how_it_conclude',
            field=models.CharField(blank=True, choices=[('EXISTOSO', 'EXISTOSO'), ('NO_EXISTOSO', 'NO_EXISTOSO'), ('EN_PROGRESO', 'EN_PROGRESO'), ('PENDIENTE', 'PENDIENTE')], default=None, max_length=30, null=True),
        ),
    ]
