# Generated by Django 5.1 on 2024-11-12 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_alter_support_how_it_conclude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('codigo_municipio', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ips',
            name='municipio_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='request.municipio'),
        ),
    ]
